sudo: required
language: go
go:
    - 1.5.1
os:
    - linux
git:
    submodules: false
install:
    - sudo pip install Pygments
    - go get github.com/spf13/hugo
    - echo "daoyinchuan.com" > ./public/CNAME
script:
    - bash ./scripts/deploy.sh